### ISSUE TITLE
I cannot install the mods

### ISSUE THREAD

**Issue by rei220392** [KH-ReFined/KH2-MAIN#9]
After installing openkh, i cannot install the mods, the following error appears.

![image](https://github.com/KH-ReFined/KH2-MAIN/assets/166129700/fe34a9ba-e7c5-44f0-86d4-211073f2c7cc)

please tell me what to do

**Comment by TopazTK** [comment]
Closing due to the issue being extremely out of date, and it being opened in the wrong repository.
